### ISSUE TITLE
Open source ?? 

### ISSUE THREAD

**Issue by vBlackOut** [AmarokStudios/Vapix#4]
Where are your source nobody can help me develop, github is made to share and not to make a commercial product rendering, your source are all in binary that's telling me you will not recover your own api password ? Or other information?

**Comment by AmarokStudios** [comment]
The API doesn't have a password.

**Comment by AmarokStudios** [comment]
I'll upload the source tomorrow though

**Comment by vBlackOut** [comment]
thanx :)

**Comment by AmarokStudios** [comment]
@vBlackOut I have uploaded the source code! Feel free to go through it and mess around with the code.
